//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChampionshipMvc3.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChampionshipMvc3.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За нас.
        /// </summary>
        public static string bgAbout {
            get {
                return ResourceManager.GetString("bgAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string bgAddress {
            get {
                return ResourceManager.GetString("bgAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Голямо игрище(лв/час).
        /// </summary>
        public static string bgBigField {
            get {
                return ResourceManager.GetString("bgBigField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмени резервацията.
        /// </summary>
        public static string bgCancelReservation {
            get {
                return ResourceManager.GetString("bgCancelReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Град.
        /// </summary>
        public static string bgCity {
            get {
                return ResourceManager.GetString("bgCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затвори.
        /// </summary>
        public static string bgClose {
            get {
                return ResourceManager.GetString("bgClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте, че искате да отмените резервацията?.
        /// </summary>
        public static string bgConfirmCancelation {
            get {
                return ResourceManager.GetString("bgConfirmCancelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакт.
        /// </summary>
        public static string bgContact {
            get {
                return ResourceManager.GetString("bgContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друго.
        /// </summary>
        public static string bgCustom {
            get {
                return ResourceManager.GetString("bgCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to График.
        /// </summary>
        public static string bgDetails {
            get {
                return ResourceManager.GetString("bgDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Край.
        /// </summary>
        public static string bgEndHour {
            get {
                return ResourceManager.GetString("bgEndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрища.
        /// </summary>
        public static string bgFields {
            get {
                return ResourceManager.GetString("bgFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип на игрището.
        /// </summary>
        public static string bgFieldType {
            get {
                return ResourceManager.GetString("bgFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Намери твоето игрище.
        /// </summary>
        public static string bgFindYourField {
            get {
                return ResourceManager.GetString("bgFindYourField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свободно.
        /// </summary>
        public static string bgFree {
            get {
                return ResourceManager.GetString("bgFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колко седмици напред?.
        /// </summary>
        public static string bgFutureWeeks {
            get {
                return ResourceManager.GetString("bgFutureWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дължина.
        /// </summary>
        public static string bgLength {
            get {
                return ResourceManager.GetString("bgLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string bgLogon {
            get {
                return ResourceManager.GetString("bgLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to лв/час.
        /// </summary>
        public static string bgLvHour {
            get {
                return ResourceManager.GetString("bgLvHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string bgName {
            get {
                return ResourceManager.GetString("bgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартал.
        /// </summary>
        public static string bgNeighbourhood {
            get {
                return ResourceManager.GetString("bgNeighbourhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следваща.
        /// </summary>
        public static string bgNextWeek {
            get {
                return ResourceManager.GetString("bgNextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не.
        /// </summary>
        public static string bgNo {
            get {
                return ResourceManager.GetString("bgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрища.
        /// </summary>
        public static string bgOwners {
            get {
                return ResourceManager.GetString("bgOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string bgPassword {
            get {
                return ResourceManager.GetString("bgPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string bgPhone {
            get {
                return ResourceManager.GetString("bgPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на игрището.
        /// </summary>
        public static string bgPlayfieldName {
            get {
                return ResourceManager.GetString("bgPlayfieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предишна.
        /// </summary>
        public static string bgPreviousWeek {
            get {
                return ResourceManager.GetString("bgPreviousWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена с осветление.
        /// </summary>
        public static string bgPriceLights {
            get {
                return ResourceManager.GetString("bgPriceLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена без осветление.
        /// </summary>
        public static string bgPriceNoLights {
            get {
                return ResourceManager.GetString("bgPriceNoLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервация.
        /// </summary>
        public static string bgReservation {
            get {
                return ResourceManager.GetString("bgReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация за резервацията.
        /// </summary>
        public static string bgReservationInformation {
            get {
                return ResourceManager.GetString("bgReservationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервирай.
        /// </summary>
        public static string bgReserve {
            get {
                return ResourceManager.GetString("bgReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избери игрище.
        /// </summary>
        public static string bgSelectPlayfield {
            get {
                return ResourceManager.GetString("bgSelectPlayfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Малко игрище(лв/час).
        /// </summary>
        public static string bgSmallField {
            get {
                return ResourceManager.GetString("bgSmallField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string bgStartHour {
            get {
                return ResourceManager.GetString("bgStartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повърхност.
        /// </summary>
        public static string bgSurface {
            get {
                return ResourceManager.GetString("bgSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заето.
        /// </summary>
        public static string bgTaken {
            get {
                return ResourceManager.GetString("bgTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        public static string bgUsername {
            get {
                return ResourceManager.GetString("bgUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ширина.
        /// </summary>
        public static string bgWidth {
            get {
                return ResourceManager.GetString("bgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string bgYes {
            get {
                return ResourceManager.GetString("bgYes", resourceCulture);
            }
        }
    }
}
